# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d1cc44dc6ce6f54db3f92536b6929e1eaa5fe8040e5cf0744e0b254d4bd5599f67a99c3300201486b37eed3ddc095bcf0fcf03bfc174605483834a082ccb848

test:
  secret_key_base: ca816ffb6cecca7886509b185bf05237d0ba0988b573cb7d90d8ddbc2d8ebdbbf1d5067525de283743d4e6d6f13f3196e5ba843a93c524f30a2d98f3641edb32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
